apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: neat
spec:
  version: "v0.1.0"
  shortDescription: Clean up Kubernetes yaml and json output to make it readable.
  homepage: https://github.com/itaysk/kubectl-neat
  description: |
    If you try to `kubectl get` resources you have just created,
    they be unreadably verbose. `kubectl-neat` cleans up that redundant information.
    Can be used as a `kubectl get` wrapper, or by piping into it.
    For example `kubectl neat pod mypod -o yaml` or
    `kubectl get pod mypod -o yaml | kubectl neat`.
  caveats: |
    This plugin depends on the following binaries -
    `jq`, `yq` and `sponge` (from `moreutils`), which should be installed by the user
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/itaysk/kubectl-neat/releases/download/v0.1.0/kubectl-neat_darwin.tar.gz
      sha256: ${sha256}
      files:
        - from: "/dist/darwin/*"
          to: "."
      bin: "./kubectl-neat"
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/itaysk/kubectl-neat/releases/download/v0.1.0/kubectl-neat_linux.tar.gz
      sha256: ${sha256}
      files:
        - from: "/dist/linux/*"
          to: "."
      bin: "./kubectl-neat"